export const REMIND_PASSWORD = 'REMIND_PASSWORD';
export const REMIND_PASSWORD_SUCCESS = 'REMIND_PASSWORD_SUCCESS';
export const REMIND_PASSWORD_ERROR = 'REMIND_PASSWORD_ERROR';

export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PASSWORD_ERROR = 'SET_PASSWORD_ERROR';
